/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main( String[] args){
        LocalDatabase.init();
    }
       /* System.out.println("starting game");
        Board board = new Board();
        Predictor p1 = new Predictor(6,(short)1);
        System.out.println("p1");
        Predictor p2 = new Predictor(6, (short)-1);
        System.out.println("p2");

        while( board.gameIsWon == false){
            System.out.println("p1 turn:");
            board.addPiece(p1.nextColumn(board));
            board.checkWin();
            board.printBoard();
            System.out.println("p2 turn:");
            board.addPiece(p2.nextColumn(board));
            board.checkWin();
            board.printBoard();
        }*/
    
}
